version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - pip3 install facebook_business==10.0.1 dentsu-pkgs

  build:
    commands:
      - cd codebuild-projects/ingest-facebook
      - chmod +x ingest_facebook.py
      - ./ingest_facebook.py

