version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - pip3 install facebook_business==17.0.0

  build:
    commands:
      - cd ingest-facebook
      - chmod +x ingest_facebook.py
      - export IS_AUTOMATED=""
      - export START_YEAR="2023"
      - export START_MONTH="09"
      - export START_DAY="20"
      - export END_YEAR="2023"
      - export END_MONTH="10"
      - export END_DAY="01"
      - ./ingest_facebook.py
