version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - pip3 install facebook_business==14.0.0

  build:
    commands:
   - cd ingest-facebook
      - chmod +x ingest_facebook.py
      - export IS_AUTOMATED=""
      - export START_YEAR="2022"
      - export START_MONTH="08"
      - export START_DAY="08"
      - export END_YEAR="2022"
      - export END_MONTH="08"
      - export END_DAY="25"
      - ./ingest_facebook.py
