version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - pip3 install facebook_business==13.0.0

  build:
    commands:
      - cd ingest-facebook
      - chmod +x ingest_facebook.py    
      - ./ingest_facebook.py 
